### ISSUE TITLE
1582年数据错误

### ISSUE THREAD

**Issue by taorandeng** [6tail/lunar-javascript#1]
1582年10月发生过特殊事件,导致中间少了10天,这里需要特别处理下.
1582年10月5日至 1582年10月14 日. 被从历法中抹去了.
具体的原因是因为以前没有逢百不润的说法(现在历法 1500 年是不润的,但是老的历法 1500 年是闰年的), 还请更新一下

**Comment by 6tail** [comment]
v1.2.3已更新，处理了这个问题。
