### ISSUE TITLE
请问日期运算能支持吗？

### ISSUE THREAD

**Issue by yx91490** [6tail/lunar-javascript#11]
比如我想要得到阴历加一年对应的日期，谢谢。

**Comment by liulin6631** [comment]
谢谢您，邮件已收到！这是来自QQ邮箱的假期自动回复邮件。

**Comment by 6tail** [comment]
粗暴点就是阴历年份+1，生成阴历对象，再转阳历。当然要考虑下大小月天数的问题，可以用LunarMonth来获取当月阴历天数。

**Comment by yx91490** [comment]
> 粗暴点就是阴历年份+1，生成阴历对象，再转阳历。当然要考虑下大小月天数的问题，可以用LunarMonth来获取当月阴历天数。

嗯，想了一下“阴历加一年对应的日期”可能没法实现，由于大小月的原因。多谢回复！
