### ISSUE TITLE
有一个小bug哦，然后还有一个期待

### ISSUE THREAD

**Issue by dooioomoo** [6tail/lunar-javascript#2]
bug： 在使用中，请将1994年7月的大暑使用.toYmdHms()来输出，你会发现秒是60.这个玩意整死我了哦。

期待：排大运那里，默认是是个数组，包含了出生年，可以不可以指定排大运的数字，不会限制在10个loop里。比如12个大运年限。我知道这很无聊，可是的确需要。

**Comment by 6tail** [comment]
已知晓，谢谢。1.2.0及以后的版本bug还比较多，暂时不建议生产使用。排大运的确实有好几个人提过了，下个版本改进。
