### ISSUE TITLE
干支错误

### ISSUE THREAD

**Issue by fishjar** [6tail/lunar-javascript#29]
2024-02-04 立春，应为 甲辰（龙）年

```sh
2024-02-04 00:00:00 闰年 星期日 水瓶座
二〇二三年腊月廿五 癸卯(兔)年 丙寅(虎)月 戊戌(狗)日 子(鼠)时 纳音[金箔金 炉中火 平地木 桑柘木] 星期日 [立春] 南方朱雀 星宿[星日马](凶) 彭祖百忌[戊不受田田主不祥 戌不吃犬作怪上床] 喜神方位[巽](东南) 阳贵神方位[艮](东北) 阴贵神方位[坤](西南) 福神方位[艮](东北) 财神方位[坎](正北) 冲[(壬辰)龙] 煞[北]
```

**Comment by 6tail** [comment]
依据国家标准《农历的编算和颁行》GB/T 33661-2017，农历年以正月初一开始，如果你想以立春开始，请阅读文档关于干支或八字的介绍。

**Comment by fishjar** [comment]
感谢提醒，之前看到 [wiki](https://zh.wikipedia.org/wiki/%E5%B9%B2%E6%94%AF) 上的介绍，被误导了：

> 夏历以[正月初一]为一年之始，而干支历[八字]则以[立春]为一年之始。

依据 `GB/T 33661-2017`：
- 农历正月初一为`生肖`和`干支年`转换日
- `干支日`则标定1949年10月1日为甲子日
- 但缺少`干支月`的说明，不清楚是按农历月转换，还是依据节气转换
