### ISSUE TITLE
HolidayUtils 获取的 2024 年春节假期数据有误

### ISSUE THREAD

**Issue by whinc** [6tail/lunar-javascript#30]
问题：通过 `HolidayUtil.getHolidays(2024, 2)` 获取 2024 年 2 月的节假日，发现  2024-02-04 出现在了结果中，而这一天并非春节假日

<img width="674" alt="image" src="https://github.com/6tail/lunar-javascript/assets/5096493/471ab7b2-82fa-45b9-ac8a-669c706b2d3f">

期望：返回的春节假期中不包含 2024-02-04 这一天

**Comment by whinc** [comment]
暂时可通过[数据修正及补充](https://6tail.cn/calendar/api.html#holiday-util.fix.html) 中给的方法临时修正数据 `HolidayUtil.fix("20240204~020240204")`，即从春节假中移除 20240204 这天

**Comment by 6tail** [comment]
@whinc 没有错，请仔细看文档，2月4日是上班，节假日分为上班和放假，work为true代表上班。

**Comment by whinc** [comment]
> @whinc 没有错，请仔细看文档，2月4日是上班，节假日分为上班和放假，work为true代表上班。

哦哦，了解了，调休日也算作节假日的部分，虽然有些不符合自觉（节假日只包含放假的日子），不过也合理，调休是因该节假日引起的，所以存储在节假日里面。我过滤下即可。
