### ISSUE TITLE
星宿有误

### ISSUE THREAD

**Issue by ClarkQi** [6tail/lunar-javascript#36]
看起来确实星宿有误，阴历1995-3-28，找了4个网站都是[胃宿(胃土雉)]，
![1](https://github.com/6tail/lunar-javascript/assets/22077184/8987d2f5-d3d4-4f03-b7bb-6c0871e22368)
![2](https://github.com/6tail/lunar-javascript/assets/22077184/ab35bf21-731d-4444-81e3-331761a53792)
![3](https://github.com/6tail/lunar-javascript/assets/22077184/f20d9726-8670-471b-bd03-8dc18f8ad303)
![4](https://github.com/6tail/lunar-javascript/assets/22077184/8e676e6e-e8ba-4ecf-a9bf-06bad597c27a)

线上API返回的是西方奎木狼
![5](https://github.com/6tail/lunar-javascript/assets/22077184/262cac99-c97f-4857-94b1-39133773f046)

**Comment by liulin6631** [comment]
谢谢您，邮件已收到！这是来自QQ邮箱的假期自动回复邮件。

**Comment by 6tail** [comment]
@ClarkQi 你怎么关闭了？
