### ISSUE TITLE
如何提交自己的作品到网站的精选案例？

### ISSUE THREAD

**Issue by whinc** [6tail/lunar-javascript#37]
感谢@6tail做出的杰出工作，让我得以实现一款功能完备且强大的日历小程序，期望能被收纳到精选案例中。

https://whinc.github.io/ucalc-website/

![image](https://github.com/6tail/lunar-javascript/assets/5096493/ca745a22-2d93-48f6-8180-3cb70260bbbe)

![image](https://github.com/6tail/lunar-javascript/assets/5096493/075f82a2-f74b-401b-83ce-215ee1b264df)

![image](https://github.com/6tail/lunar-javascript/assets/5096493/e292a38f-693b-44c8-b36b-a306f9de4bc5)

**Comment by 6tail** [comment]
已收录。

**Comment by whinc** [comment]
> 已收录。

你好，能否抽空更新下示例，近期新增了“佛历”和“道历”，这两个都是 lunar-javascript 的特色功能，希望能更新到示例中展示

|佛历|道历|
|----|-----|
|![image](https://github.com/user-attachments/assets/536261c9-623a-4f28-803a-b82332612b42)|![image](https://github.com/user-attachments/assets/08879b84-c376-41bd-8c1c-379c80ec0c3c)|

**Comment by whinc** [comment]
你好，最近升级到最新的 lunar-typescript 版本，并对 UI 做了一些大的调整，如果方便麻烦帮更新下示例

|万年历|黄历|
|----|-----|
|![Image](https://github.com/user-attachments/assets/fa17d077-94f9-4c74-a075-4d972f0401d8)|<img width="1242" height="2688" alt="Image" src="https://github.com/user-attachments/assets/8f5ef195-19bc-48c5-bf77-01dbd0162379" />|

|佛历|道历|
|----|-----|
|<img width="1242" height="2688" alt="Image" src="https://github.com/user-attachments/assets/b1da9c05-ed22-4276-a33f-9eb1df4a2ed8" />|![Image](https://github.com/user-attachments/assets/b884deea-487e-4fb2-9817-a063c521800b)|

**Comment by liulin6631** [comment]
谢谢您，邮件已收到！这是来自QQ邮箱的假期自动回复邮件。
