### ISSUE TITLE
二十四节气时间差异

### ISSUE THREAD

**Issue by pengyuanhong** [6tail/lunar-javascript#45]
二十四节气时间与其它多个平台对比后有些许差异，以2024年立春时间为例。
如：

当前插件：
    立春时间：2024-02-04 16:27:05

1、日历网：https://www.rili.com.cn/24jieqi/
    立春时间：2024-02-04 16:26:53

2、便民查询：https://jieqi.bmcx.com/2024_lichun__jieqi/
    立春时间：2024-02-04 16:26:53

3、查查达：https://jieqi.chacd.com/2024-1/
    立春时间：2024-02-04 16:26:53

**Comment by 6tail** [comment]
如果你认为他们的更准，那你可以放弃使用本库了。本库节气计算采用的寿星天文历的算法。

**Comment by 6tail** [comment]
顺便建议你去中国科学院紫金山天文台查一下立春时间。

**Comment by pengyuanhong** [comment]
> 顺便建议你去中国科学院紫金山天文台查一下立春时间。

非常感谢！

**Comment by pengyuanhong** [comment]
> 顺便建议你去中国科学院紫金山天文台查一下立春时间。

非常感谢！刚看了下  中国科学院紫金山天文台 《2024年日历资料》，其它节气时间也是有些许差异（如：谷雨、芒种、秋分等）。不过前面列举的几个平台也存在差异。

**Comment by XingXingLeo** [comment]
<img width="821" alt="image" src="https://github.com/user-attachments/assets/befc5878-03b2-4e84-a687-e7219e196242">
作者你好，我看了寿星天文历的网站，这里也是26分53秒，但是标注了是定气法。
另外，我看了寿星天文历法2024年的冬至是2024-12-21 17:20:20，而lunar-js上是2024-12-21 17:20:32，也是相差了12秒。

**Comment by liulin6631** [comment]
谢谢您，邮件已收到！这是来自QQ邮箱的假期自动回复邮件。

**Comment by 6tail** [comment]
> <img alt="image" width="821" src="https://private-user-images.githubusercontent.com/17746383/391338888-befc5878-03b2-4e84-a687-e7219e196242.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNDA0ODksIm5iZiI6MTczMzE0MDE4OSwicGF0aCI6Ii8xNzc0NjM4My8zOTEzMzg4ODgtYmVmYzU4NzgtMDNiMi00ZTg0LWE2ODctZTcyMTllMTk2MjQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDExNDk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2ZWRiMzAwOTdiZWIxMmMxYWU1M2I5Zjg1YjFhYjY4YmMzYTQ5NGMwNjc1NjE2ZjRkMmVhOGZlMDQyZTY4MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uMkPtzBAEtyl5srDWZUZS1W9Ah-EHYiwnNDQhS5Ow20"> 作者你好，我看了寿星天文历的网站，这里也是26分53秒，但是标注了是定气法。 另外，我看了寿星天文历法2024年的冬至是2024-12-21 17:20:20，而lunar-js上是2024-12-21 17:20:32，也是相差了12秒。 我对比了一下，从1899年-2010年期间的冬至都是能对上的。但从2011年开始，冬至日就比寿星天文历上就开始有几秒到十几秒的差别了。

我文档写了，lunar基于寿星5.10版本，你用的5.05，有误差自然是正常现象。

**Comment by XingXingLeo** [comment]
> 我文档写了，lunar基于寿星5.10版本，你用的5.05，有误差自然是正常现象。

好的，我找到5.10版试了一下，确实是这样的，抱歉打扰了。

**Comment by pengyuanhong** [comment]
completed

**Comment by XingXingLeo** [comment]
> > <img alt="image" width="821" src="https://private-user-images.githubusercontent.com/17746383/391338888-befc5878-03b2-4e84-a687-e7219e196242.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNDA0ODksIm5iZiI6MTczMzE0MDE4OSwicGF0aCI6Ii8xNzc0NjM4My8zOTEzMzg4ODgtYmVmYzU4NzgtMDNiMi00ZTg0LWE2ODctZTcyMTllMTk2MjQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDExNDk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2ZWRiMzAwOTdiZWIxMmMxYWU1M2I5Zjg1YjFhYjY4YmMzYTQ5NGMwNjc1NjE2ZjRkMmVhOGZlMDQyZTY4MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uMkPtzBAEtyl5srDWZUZS1W9Ah-EHYiwnNDQhS5Ow20"> 作者你好，我看了寿星天文历的网站，这里也是26分53秒，但是标注了是定气法。 另外，我看了寿星天文历法2024年的冬至是2024-12-21 17:20:20，而lunar-js上是2024-12-21 17:20:32，也是相差了12秒。 我对比了一下，从1899年-2010年期间的冬至都是能对上的。但从2011年开始，冬至日就比寿星天文历上就开始有几秒到十几秒的差别了。
> 
> 我文档写了，lunar基于寿星5.10版本，你用的5.05，有误差自然是正常现象。

想要继续请教一下，后来我发现，这几秒到十几米的差别是为js版本和golang版本计算的差别。比如我使用lunar-go1.43版本计算2024年的冬至是2024-12-21 17:20:19，用lunar-js计算2024年的冬至是2024-12-21 17:20:32。
能请教一下，这个是语言本身导致的计算误差还是代码不同导致的吗？

**Comment by Crazydear** [comment]
> > > <img alt="image" width="821" src="https://private-user-images.githubusercontent.com/17746383/391338888-befc5878-03b2-4e84-a687-e7219e196242.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNDA0ODksIm5iZiI6MTczMzE0MDE4OSwicGF0aCI6Ii8xNzc0NjM4My8zOTEzMzg4ODgtYmVmYzU4NzgtMDNiMi00ZTg0LWE2ODctZTcyMTllMTk2MjQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDExNDk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2ZWRiMzAwOTdiZWIxMmMxYWU1M2I5Zjg1YjFhYjY4YmMzYTQ5NGMwNjc1NjE2ZjRkMmVhOGZlMDQyZTY4MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uMkPtzBAEtyl5srDWZUZS1W9Ah-EHYiwnNDQhS5Ow20"> 作者你好，我看了寿星天文历的网站，这里也是26分53秒，但是标注了是定气法。 另外，我看了寿星天文历法2024年的冬至是2024-12-21 17:20:20，而lunar-js上是2024-12-21 17:20:32，也是相差了12秒。 我对比了一下，从1899年-2010年期间的冬至都是能对上的。但从2011年开始，冬至日就比寿星天文历上就开始有几秒到十几秒的差别了。
> > 
> > 我文档写了，lunar基于寿星5.10版本，你用的5.05，有误差自然是正常现象。
> 
> 想要继续请教一下，后来我发现，这几秒到十几米的差别是为js版本和golang版本计算的差别。比如我使用lunar-go1.43版本计算2024年的冬至是2024-12-21 17:20:19，用lunar-js计算2024年的冬至是2024-12-21 17:20:32。
> 能请教一下，这个是语言本身导致的计算误差还是代码不同导致的吗？

有没有可能是你使用lunar-js版本的问题，最新已经到1.7.3了，1.7.1版本更新了T参数

**Comment by 6tail** [comment]
> > > <img alt="image" width="821" src="https://private-user-images.githubusercontent.com/17746383/391338888-befc5878-03b2-4e84-a687-e7219e196242.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMxNDA0ODksIm5iZiI6MTczMzE0MDE4OSwicGF0aCI6Ii8xNzc0NjM4My8zOTEzMzg4ODgtYmVmYzU4NzgtMDNiMi00ZTg0LWE2ODctZTcyMTllMTk2MjQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAyVDExNDk0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2ZWRiMzAwOTdiZWIxMmMxYWU1M2I5Zjg1YjFhYjY4YmMzYTQ5NGMwNjc1NjE2ZjRkMmVhOGZlMDQyZTY4MzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uMkPtzBAEtyl5srDWZUZS1W9Ah-EHYiwnNDQhS5Ow20"> 作者你好，我看了寿星天文历的网站，这里也是26分53秒，但是标注了是定气法。 另外，我看了寿星天文历法2024年的冬至是2024-12-21 17:20:20，而lunar-js上是2024-12-21 17:20:32，也是相差了12秒。 我对比了一下，从1899年-2010年期间的冬至都是能对上的。但从2011年开始，冬至日就比寿星天文历上就开始有几秒到十几秒的差别了。
> > 
> > 
> > 我文档写了，lunar基于寿星5.10版本，你用的5.05，有误差自然是正常现象。
> 
> 想要继续请教一下，后来我发现，这几秒到十几米的差别是为js版本和golang版本计算的差别。比如我使用lunar-go1.43版本计算2024年的冬至是2024-12-21 17:20:19，用lunar-js计算2024年的冬至是2024-12-21 17:20:32。 能请教一下，这个是语言本身导致的计算误差还是代码不同导致的吗？

建议用lunar最新版本。
