### ISSUE TITLE
Lunar.fromYmd 报错

### ISSUE THREAD

**Issue by CarbonPool** [6tail/lunar-javascript#48]
今天是2024年12月30日，还是我用法不对，Lunar.fromYmd(2024,12,30)，就会提示only 29 days in lunar year 2024 month 12，如果是Lunar.fromDate(new Date())，则不会报错

**Comment by liulin6631** [comment]
谢谢您，邮件已收到！这是来自QQ邮箱的假期自动回复邮件。

**Comment by CarbonPool** [comment]
好像是需要传入农历日期
