### ISSUE TITLE
阴历的getDayInChinese方法，不同的实例化方式，得到的结果不同

### ISSUE THREAD

**Issue by wes0310** [6tail/lunar-javascript#5]
![image](https://user-images.githubusercontent.com/14003807/153364337-13d29e37-99be-4e80-858b-24a0f3530174.png)

**Comment by liulin6631** [comment]
谢谢您，邮件已收到！这是来自QQ邮箱的假期自动回复邮件。

**Comment by wes0310** [comment]
例如今天是2022年2月10日，使用fromDate方法实施化的结果是正月初十，而使用fromYmd方法实施化的结果是日期结果一样

**Comment by 6tail** [comment]
请仔细阅读文档，Lunar.fromDate方法，参数是阴历年月日，不是阳历年月日。

**Comment by wes0310** [comment]
> 请仔细阅读文档，Lunar.fromDate方法，参数是阴历年月日，不是阳历年月日。
Lunar.fromDate和fromYmd的参数不一样么

**Comment by 6tail** [comment]
说错了，Lunar.fromDate参数是阳历日期对象，Lunar.fromYmd参数是阴历年月日。
