### ISSUE TITLE
2022-4-5 节日没显示清明节

### ISSUE THREAD

**Issue by imsheng** [6tail/lunar-javascript#7]
如题

var d = Solar.fromYmd(2022, 4, 5);
var l = d.getFestivals();

**Comment by 6tail** [comment]
请仔细阅读文档。

**Comment by imsheng** [comment]
是什么问题?

**Comment by 6tail** [comment]
请仔细阅读文档，阳历节日、阴历节日、法定假日不是全部放在阳历的getFestivals方法返回的。
