### ISSUE TITLE
Vue3调用getYun()发生错误: Converting circular structure to JSON

### ISSUE THREAD

**Issue by jhyvictory** [6tail/lunar-javascript#8]
Vue3调用getYun()发生错误：

shared.esm-bundler.js:448 Uncaught (in promise) TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property '_p' -> object with constructor 'Object'
    |     property 'eightChar' -> object with constructor 'Object'
    |     property '_p' -> object with constructor 'Object'
    --- property 'lunar' closes the circle

**Comment by 6tail** [comment]
不能将lunar中的对象直接转为json字符串，存在循环引用。
