### ISSUE TITLE
八字的月份计算错误

### ISSUE THREAD

**Issue by yiyang-1125** [6tail/lunar-javascript#9]
今天 2022 年5月5日
var lunar = Lunar.fromDate(new Date());
var d = lunar.getEightChar();

console.log(d);
输出：
壬寅 甲辰 戊午 丁巳

但是万年历，2022年5月5日是乙巳月

**Comment by 6tail** [comment]
八字和万年历是两回事，谢谢，八字跨月是要精确到时刻的。

**Comment by yiyang-1125** [comment]
谢谢，不好意思。
